dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: g66DkyJBXKpaf+YSr6/Yaz8Ov5o7LJtwRJbofXEGm7GEkrp7Qv3nZDPJPZTwqkNUMujftZUwgOKLLzvSAP/wdKb00cJ/AbRkSX7Oxld5z+pGK9UdpM8bhqcPfFsjuD7iuJmdKIpWM4/e4rjZg0uofF2iQq93kLpGpbIbV/B/8gKKmGUUYp6qCJRnCIOGxGrYCvSmT6I+fJyq/MT4ekZQ8yWeQa2c1mIMGPEaUdV2kbKeE3HXKgMP0YfZM/Y/mwOd4f3KDiWvlNYB+Vn9yFF0IN3igUB4D1n12mVm+aBg9D6Ljfts5qJFvitjFiTz5qIUSETZqlCChCHQVDFK9gfRWJ5FrJbk18MAifeQrmeuoba1l+qoxuY4Esvas0JT8L55KnI8VgaDkwH7fWkzYLDovRxBAcmliyKhThCzj0w3iPA/75kQ/zjVFxhV5aXliVODHiDEBXWFk36V5F8rg0O1NiEJOYV3PVRNbstolY6hj0nT9MdefGfbKG8gpZPf7CVhMMz3stuDMRV/skwo/h7QlFmQvf4SCK2cXYa93KwowaXj13REupP01yHwezXtUTnzyzn1hilwXoZ2lkcJmfLSEPclu6J811pF9Ebu3/OQejBLofljH0g6ie++Pd9Wk0Cbl9ObpBbYviwEmWKUCEMj3mFPVgwy/SVDKANZrcGnvnw=
