---
name: Build
'on':
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PKGFORGE_STATEFILE: "/tmp/pkgforge"
    steps:
    - name: Run base CI
      uses: akerl/.github/actions/base-pkgforge@main
