name: Release
on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
env:
  PKGFORGE_STATEFILE: /tmp/pkgforge
jobs:
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Make
      run: make release
