name: Release
on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
env:
  PKGFORGE_STATEFILE: /tmp/pkgforge
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: akerl/action-checkout@v2.0.0
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Make
      run: make release
